In [29]:
import pandas as pd
import os

# Define paths to data files
RAW_DATA_DIR = os.path.join("..","data","raw")

PATH_FTE_ACTUAL = os.path.join(RAW_DATA_DIR, "fte-enrollments-actual.csv")
PATH_FTE_TARGET = os.path.join(RAW_DATA_DIR, "fte-enrollments-target.csv")
PATH_GRANTS = os.path.join(RAW_DATA_DIR, "operating-grants.csv")
PATH_HEADCOUNT = os.path.join(RAW_DATA_DIR, "student-headcount-by-region.csv")

# Load the datasets
df_fte_actual = pd.read_csv(PATH_FTE_ACTUAL)
df_fte_target = pd.read_csv(PATH_FTE_TARGET)
df_grants = pd.read_csv(PATH_GRANTS)
df_headcount = pd.read_csv(PATH_HEADCOUNT)

In [30]:
# Inspection of fte_actual dataset
df_fte_actual.info()
display(df_fte_actual.head())
display(df_fte_actual.describe())

<class 'pandas.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fiscal Year  275 non-null    str
 1   Institution  275 non-null    str
 2   FTE Actual   275 non-null    str
 3   Unnamed: 3   0 non-null      float64
 4   Unnamed: 4   0 non-null      float64
 5   Unnamed: 5   0 non-null      float64
dtypes: float64(3), str(3)
memory usage: 13.0 KB

,Fiscal Year,Institution,FTE Actual,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,FY 2014/15,British Columbia Institute of Technology,"13,279",NaN,NaN,NaN
1,FY 2014/15,Camosun College,"6,469",NaN,NaN,NaN
2,FY 2014/15,Capilano University,"4,789",NaN,NaN,NaN
3,FY 2014/15,College of New Caledonia,"1,871",NaN,NaN,NaN
4,FY 2014/15,College of the Rockies,"1,526",NaN,NaN,NaN

       Unnamed: 3  Unnamed: 4  Unnamed: 5
count         0.0         0.0         0.0
mean          NaN         NaN         NaN
std           NaN         NaN         NaN
min           NaN         NaN         NaN
25%           NaN         NaN         NaN
50%           NaN         NaN         NaN
75%           NaN         NaN         NaN
max           NaN         NaN         NaN

In [31]:
# Inspection of fte_target dataset
df_fte_target.info()
display(df_fte_target.head())
display(df_fte_target.describe())

<class 'pandas.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fiscal Year  275 non-null    str
 1   Institution  275 non-null    str
 2   FTE Target   275 non-null    str
 3   Unnamed: 3   0 non-null      float64
 4   Unnamed: 4   0 non-null      float64
 5   Unnamed: 5   0 non-null      float64
dtypes: float64(3), str(3)
memory usage: 13.0 KB

,Fiscal Year,Institution,FTE Target,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,FY 2016/17,British Columbia Institute of Technology,"12,100",NaN,NaN,NaN
1,FY 2016/17,Camosun College,"7,073",NaN,NaN,NaN
2,FY 2016/17,Capilano University,"5,449",NaN,NaN,NaN
3,FY 2016/17,Coast Mountain College,"1,676",NaN,NaN,NaN
4,FY 2016/17,College of New Caledonia,"3,125",NaN,NaN,NaN

       Unnamed: 3  Unnamed: 4  Unnamed: 5
count         0.0         0.0         0.0
mean          NaN         NaN         NaN
std           NaN         NaN         NaN
min           NaN         NaN         NaN
25%           NaN         NaN         NaN
50%           NaN         NaN         NaN
75%           NaN         NaN         NaN
max           NaN         NaN         NaN

In [32]:
# Inspection of grants dataset
df_grants.info()
display(df_grants.head())
display(df_grants.describe())

<class 'pandas.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fiscal Year      275 non-null    str
 1   Institution      275 non-null    str
 2   Operating Grant  275 non-null    str
dtypes: str(3)
memory usage: 6.6 KB

  Fiscal Year                               Institution Operating Grant
0  FY 2015/16  British Columbia Institute of Technology    $112,235,228
1  FY 2015/16                           Camosun College     $47,631,510
2  FY 2015/16                       Capilano University     $36,304,537
3  FY 2015/16                  College of New Caledonia     $28,621,013
4  FY 2015/16                    College of the Rockies     $16,837,896

       Fiscal Year                               Institution Operating Grant
count          275                                       275             275
unique          11                                        25             275
top     FY 2015/16  British Columbia Institute of Technology    $112,235,228
freq            25                                        11               1

In [33]:
# All datasets have 26 rows. Check whether the institutions are the samme across datasets
actual_insts = set(df_fte_actual['Institution'].dropna().unique())
target_insts = set(df_fte_target['Institution'].dropna().unique())
grants_insts = set(df_grants['Institution'].dropna().unique())

# Identify mismatches between target and actual
print("In Target but not Actual:", target_insts - actual_insts)
print("In Actual but not Target:", actual_insts - target_insts)

# Identify mismatches grants and actual
print("In Grants but not Actual:", grants_insts - actual_insts)
print("In Actual but not Grants:", actual_insts - grants_insts)

In Target but not Actual: {'Thompson Rivers University ', 'Vancouver Island University ', 'University of the Fraser Valley ', 'Capilano University ', 'Kwantlen Polytechnic University ', 'Nicola Valley Institute of Technology '}
In Actual but not Target: {'Capilano University', 'Nicola Valley Institute of Technology', 'University of the Fraser Valley', 'Vancouver Island University', 'Kwantlen Polytechnic University', 'Thompson Rivers University'}
In Grants but not Actual: set()
In Actual but not Grants: set()

In [34]:
# Verify that string stripping resolves target vs actual discrepancies
actual_clean = set(df_fte_actual['Institution'].dropna().str.strip().unique())
target_clean = set(df_fte_target['Institution'].dropna().str.strip().unique())
grants_clean = set(df_grants['Institution'].dropna().str.strip().unique())

unmatched_target = actual_clean ^ target_clean
unmatched_grants = actual_clean ^ grants_clean

print(f"Unmatched Target institutions after strip: {len(unmatched_target)}")
print(f"Unmatched Grants institutions after strip: {len(unmatched_grants)}")

if len(unmatched_target) == 0 and len(unmatched_grants) == 0:
    print("`.str.strip()` resolves all institution name mismatches across datasets")
else:
    print(f"Remaining discrepancies: {unmatched_target | unmatched_grants}")

Unmatched Target institutions after strip: 0
Unmatched Grants institutions after strip: 0
`.str.strip()` resolves all institution name mismatches across datasets

In [35]:
# Examine fiscal year coverage across datasets
actual_years = set(df_fte_actual['Fiscal Year'].dropna().unique())
target_years = set(df_fte_target['Fiscal Year'].dropna().unique())
grants_years = set(df_grants['Fiscal Year'].dropna().unique())

# Identify fiscal year overlap and boundary differences
common_years = actual_years & target_years & grants_years
all_years = actual_years | target_years | grants_years

print(f"Total distinct fiscal years across all files: {len(all_years)}")
print(f"Fiscal years common to all three datasets: {len(common_years)} years ({min(common_years)} to {max(common_years)})")
print("Years in Actual but missing in Target:", sorted(list(actual_years - target_years)))
print("Years in Target but missing in Actual:", sorted(list(target_years - actual_years)))

Total distinct fiscal years across all files: 13
Fiscal years common to all three datasets: 9 years (FY 2016/17 to FY 2024/25)
Years in Actual but missing in Target: ['FY 2014/15', 'FY 2015/16']
Years in Target but missing in Actual: ['FY 2025/26', 'FY 2026/27']

In [36]:
# Inspection of headcount dataset
df_headcount.info()
display(df_headcount.head())
display(df_headcount.describe())

# Include df_headcount in institution whitespace checking
headcount_insts = set(df_headcount['Institution'].dropna().unique())
print("In Headcount but not Actual:", headcount_insts - actual_insts)

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Academic Year                520 non-null    str
 1   Economic Development Region  520 non-null    str
 2   Institution                  520 non-null    str
 3   International/Domestic       520 non-null    str
 4   Headcount                    517 non-null    str
dtypes: str(5)
memory usage: 20.4 KB

,Academic Year,Economic Development Region,Institution,International/Domestic,Headcount
0,2015/2016,Cariboo/North,CMTN,DOMESTIC,4665
1,2015/2016,Cariboo/North,CMTN,INTERNATIONAL,15
2,2015/2016,Cariboo/North,CNC,DOMESTIC,7965
3,2015/2016,Cariboo/North,CNC,INTERNATIONAL,505
4,2015/2016,Cariboo/North,NLC,DOMESTIC,5570

,Academic Year,Economic Development Region,Institution,International/Domestic,Headcount
count,520,520,520,520,517
unique,10,4,26,2,471
top,2015/2016,Mainland/Southwest,CMTN,DOMESTIC,*
freq,52,220,20,260,4

In Headcount but not Actual: {'OKAN', 'UVIC', 'SFU', 'UBCO', 'JIBC', 'UBCV', 'KPU', 'COTR', 'CAPU', 'RRU', 'CNC', 'BCIT', 'DOUG', 'SEL', 'TRU', 'NIC', 'NLC', 'VCC', 'CAM', 'CMTN', 'UNBC', 'LANG', 'NVIT', 'UFV', 'VIU', 'ECU'}